# Generated by Django 4.1.6 on 2023-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190211_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='rPPGe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('description', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
